In [1]:
#导入包
import pandas as pd
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [2]:
#导入数据集
from sklearn import datasets
iris=datasets.load_iris()

In [3]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [4]:
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [5]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [16]:
#切分数据集
Xtrain, Xtest, ytrain, ytest = train_test_split(iris.data,
                                                iris.target,
                                                random_state=42)

In [17]:
len(Xtrain)

112

In [18]:
len(Xtest)

38

In [19]:
ytrain

array([0, 0, 2, 1, 1, 0, 0, 1, 2, 2, 1, 2, 1, 2, 1, 0, 2, 1, 0, 0, 0, 1,
       2, 0, 0, 0, 1, 0, 1, 2, 0, 1, 2, 0, 2, 2, 1, 1, 2, 1, 0, 1, 2, 0,
       0, 1, 1, 0, 2, 0, 0, 1, 1, 2, 1, 2, 2, 1, 0, 0, 2, 2, 0, 0, 0, 1,
       2, 0, 2, 2, 0, 1, 1, 2, 1, 2, 0, 2, 1, 2, 1, 1, 1, 0, 1, 1, 0, 1,
       2, 2, 0, 1, 2, 2, 0, 2, 0, 1, 2, 2, 1, 2, 1, 1, 2, 2, 0, 1, 2, 0,
       1, 2])

In [20]:
ytest

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0])

In [21]:
#建模
clf = GaussianNB()
clf.fit(Xtrain, ytrain)

GaussianNB(priors=None)

In [22]:
#在测试集上执行预测，proba导出的是每个样本属于某类的概率
clf.predict(Xtest)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0])

In [23]:
clf.predict_proba(Xtest)

array([[5.97926853e-094, 9.95499546e-001, 4.50045384e-003],
       [1.00000000e+000, 1.52146968e-013, 1.07136902e-020],
       [1.71330808e-299, 6.04667826e-012, 1.00000000e+000],
       [2.88508207e-096, 9.76485329e-001, 2.35146713e-002],
       [1.36797133e-109, 8.51147229e-001, 1.48852771e-001],
       [1.00000000e+000, 4.74962788e-013, 4.28854236e-021],
       [3.25153316e-053, 9.99959350e-001, 4.06500520e-005],
       [1.09216160e-176, 1.05015117e-006, 9.99998950e-001],
       [3.27169186e-098, 9.93646597e-001, 6.35340277e-003],
       [1.17401351e-060, 9.99944993e-001, 5.50073382e-005],
       [1.00765817e-153, 5.02929583e-004, 9.99497070e-001],
       [1.00000000e+000, 7.95517827e-017, 5.80301835e-025],
       [1.00000000e+000, 1.83324108e-016, 2.96899989e-024],
       [1.00000000e+000, 1.81709952e-016, 2.19054140e-024],
       [1.00000000e+000, 2.58611124e-016, 6.24907433e-024],
       [4.90534771e-110, 5.45081346e-001, 4.54918654e-001],
       [3.16184825e-207, 5.32942939e-007

In [24]:
#测试准确率
accuracy_score(ytest, clf.predict(Xtest))

1.0

In [25]:
import numpy as np
import pandas as pd
import random

In [26]:
dataSet =pd.read_csv('iris.txt',header = None)
dataSet.head()

0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [27]:
dataSet.shape

(150, 5)

In [28]:
def randSplit(dataSet, rate):
    l = list(dataSet.index) #提取出索引
    random.shuffle(l) #随机打乱索引
    dataSet.index = l #将打乱后的索引重新赋值给原数据集
    n = dataSet.shape[0] #总行数
    m = int(n * rate) #训练集的数量
    train = dataSet.loc[range(m), :] #提取前m个记录作为训练集
    test = dataSet.loc[range(m, n), :] #剩下的作为测试集
    dataSet.index = range(dataSet.shape[0]) #更新原数据集的索引
    test.index = range(test.shape[0]) #更新测试集的索引
    return train, test

In [29]:
 l = list(dataSet.index)

In [31]:
print(l)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149]


In [33]:
random.shuffle(l)
dataSet.index = l

In [36]:
n = dataSet.shape[0] #总行数
m = int(n * 0.8) #训练集的数量

In [37]:
train = dataSet.loc[range(m), :]

In [38]:
train

0    1    2    3                4
0    4.6  3.6  1.0  0.2      Iris-setosa
1    6.9  3.1  5.1  2.3   Iris-virginica
2    5.0  2.3  3.3  1.0  Iris-versicolor
3    6.0  3.4  4.5  1.6  Iris-versicolor
4    5.7  2.9  4.2  1.3  Iris-versicolor
5    6.3  2.7  4.9  1.8   Iris-virginica
6    6.3  2.5  4.9  1.5  Iris-versicolor
7    6.4  2.7  5.3  1.9   Iris-virginica
8    5.1  2.5  3.0  1.1  Iris-versicolor
9    6.2  2.8  4.8  1.8   Iris-virginica
10   5.1  3.7  1.5  0.4      Iris-setosa
11   4.4  3.2  1.3  0.2      Iris-setosa
12   7.7  3.0  6.1  2.3   Iris-virginica
13   5.6  2.5  3.9  1.1  Iris-versicolor
14   5.0  3.3  1.4  0.2      Iris-setosa
15   4.4  2.9  1.4  0.2      Iris-setosa
16   6.3  2.9  5.6  1.8   Iris-virginica
17   5.4  3.9  1.3  0.4      Iris-setosa
18   5.1  3.5  1.4  0.3      Iris-setosa
19   6.7  3.3  5.7  2.1   Iris-virginica
20   6.1  2.8  4.7  1.2  Iris-versicolor
21   4.9  3.0  1.4  0.2      Iris-setosa
22   6.3  2.8  5.1  1.5   Iris-virginica
23   5.1  3.8  1.9  0.4      Iris-setosa
24   5.6  3.0  4.1  1.3  Iris-versicolor
25   6.3  2.3  4.4  1.3  Iris-versicolor
26   6.5  3.0  5.5  1.8   Iris-virginica
27   7.7  3.8  6.7  2.2   Iris-virginica
28   7.7  2.8  6.7  2.0   Iris-virginica
29   4.8  3.0  1.4  0.1      Iris-setosa
..   ...  ...  ...  ...              ...
90   6.7  3.1  4.7  1.5  Iris-versicolor
91   6.2  2.9  4.3  1.3  Iris-versicolor
92   4.9  2.5  4.5  1.7   Iris-virginica
93   5.0  3.5  1.6  0.6      Iris-setosa
94   5.2  3.5  1.5  0.2      Iris-setosa
95   5.9  3.0  5.1  1.8   Iris-virginica
96   6.5  3.0  5.8  2.2   Iris-virginica
97   4.8  3.1  1.6  0.2      Iris-setosa
98   6.5  2.8  4.6  1.5  Iris-versicolor
99   6.7  3.1  4.4  1.4  Iris-versicolor
100  5.2  3.4  1.4  0.2      Iris-setosa
101  4.5  2.3  1.3  0.3      Iris-setosa
102  5.0  3.0  1.6  0.2      Iris-setosa
103  5.0  3.4  1.5  0.2      Iris-setosa
104  5.6  2.9  3.6  1.3  Iris-versicolor
105  7.9  3.8  6.4  2.0   Iris-virginica
106  5.8  2.7  3.9  1.2  Iris-versicolor
107  6.0  2.2  5.0  1.5   Iris-virginica
108  5.7  4.4  1.5  0.4      Iris-setosa
109  4.6  3.4  1.4  0.3      Iris-setosa
110  5.1  3.3  1.7  0.5      Iris-setosa
111  6.3  3.3  4.7  1.6  Iris-versicolor
112  5.0  2.0  3.5  1.0  Iris-versicolor
113  6.1  3.0  4.6  1.4  Iris-versicolor
114  6.0  2.9  4.5  1.5  Iris-versicolor
115  6.0  3.0  4.8  1.8   Iris-virginica
116  5.5  2.6  4.4  1.2  Iris-versicolor
117  6.6  2.9  4.6  1.3  Iris-versicolor
118  5.5  2.5  4.0  1.3  Iris-versicolor
119  4.9  3.1  1.5  0.1      Iris-setosa

[120 rows x 5 columns]

In [41]:
test = dataSet.loc[range(m, n), :]

In [43]:
test.index = range(test.shape[0])
test

0    1    2    3                4
0   5.5  2.4  3.8  1.1  Iris-versicolor
1   4.3  3.0  1.1  0.1      Iris-setosa
2   6.0  2.2  4.0  1.0  Iris-versicolor
3   5.0  3.2  1.2  0.2      Iris-setosa
4   4.6  3.1  1.5  0.2      Iris-setosa
5   5.7  2.8  4.5  1.3  Iris-versicolor
6   4.9  3.1  1.5  0.1      Iris-setosa
7   6.3  3.3  6.0  2.5   Iris-virginica
8   5.9  3.0  4.2  1.5  Iris-versicolor
9   4.9  2.4  3.3  1.0  Iris-versicolor
10  5.7  3.8  1.7  0.3      Iris-setosa
11  4.8  3.4  1.6  0.2      Iris-setosa
12  5.6  2.7  4.2  1.3  Iris-versicolor
13  5.1  3.8  1.5  0.3      Iris-setosa
14  5.8  4.0  1.2  0.2      Iris-setosa
15  7.1  3.0  5.9  2.1   Iris-virginica
16  7.0  3.2  4.7  1.4  Iris-versicolor
17  6.7  3.0  5.2  2.3   Iris-virginica
18  6.6  3.0  4.4  1.4  Iris-versicolor
19  6.2  2.2  4.5  1.5  Iris-versicolor
20  6.4  3.1  5.5  1.8   Iris-virginica
21  5.0  3.4  1.6  0.4      Iris-setosa
22  7.6  3.0  6.6  2.1   Iris-virginica
23  6.9  3.1  4.9  1.5  Iris-versicolor
24  5.7  2.8  4.1  1.3  Iris-versicolor
25  5.1  3.8  1.6  0.2      Iris-setosa
26  6.1  2.9  4.7  1.4  Iris-versicolor
27  6.1  2.8  4.0  1.3  Iris-versicolor
28  5.1  3.5  1.4  0.2      Iris-setosa
29  7.2  3.6  6.1  2.5   Iris-virginica

In [44]:
train,test=randSplit(dataSet, 0.8)

In [45]:
train

0    1    2    3                4
0    5.2  3.5  1.5  0.2      Iris-setosa
1    6.3  3.4  5.6  2.4   Iris-virginica
2    4.8  3.0  1.4  0.3      Iris-setosa
3    7.3  2.9  6.3  1.8   Iris-virginica
4    4.8  3.4  1.9  0.2      Iris-setosa
5    4.9  3.1  1.5  0.1      Iris-setosa
6    5.1  3.8  1.6  0.2      Iris-setosa
7    6.0  2.2  5.0  1.5   Iris-virginica
8    6.0  2.2  4.0  1.0  Iris-versicolor
9    6.1  2.6  5.6  1.4   Iris-virginica
10   6.2  2.8  4.8  1.8   Iris-virginica
11   6.3  3.3  6.0  2.5   Iris-virginica
12   6.5  3.0  5.5  1.8   Iris-virginica
13   5.8  4.0  1.2  0.2      Iris-setosa
14   5.8  2.6  4.0  1.2  Iris-versicolor
15   6.7  3.1  4.7  1.5  Iris-versicolor
16   6.0  3.4  4.5  1.6  Iris-versicolor
17   5.8  2.7  4.1  1.0  Iris-versicolor
18   6.4  3.2  5.3  2.3   Iris-virginica
19   5.8  2.7  5.1  1.9   Iris-virginica
20   5.5  2.3  4.0  1.3  Iris-versicolor
21   5.4  3.7  1.5  0.2      Iris-setosa
22   5.0  3.3  1.4  0.2      Iris-setosa
23   6.1  2.9  4.7  1.4  Iris-versicolor
24   4.8  3.4  1.6  0.2      Iris-setosa
25   5.0  3.4  1.5  0.2      Iris-setosa
26   5.5  3.5  1.3  0.2      Iris-setosa
27   6.0  2.9  4.5  1.5  Iris-versicolor
28   4.7  3.2  1.6  0.2      Iris-setosa
29   5.6  2.5  3.9  1.1  Iris-versicolor
..   ...  ...  ...  ...              ...
90   5.5  4.2  1.4  0.2      Iris-setosa
91   6.3  2.5  4.9  1.5  Iris-versicolor
92   6.5  3.2  5.1  2.0   Iris-virginica
93   5.4  3.4  1.7  0.2      Iris-setosa
94   5.0  3.5  1.3  0.3      Iris-setosa
95   6.3  2.9  5.6  1.8   Iris-virginica
96   6.6  2.9  4.6  1.3  Iris-versicolor
97   6.8  2.8  4.8  1.4  Iris-versicolor
98   7.2  3.6  6.1  2.5   Iris-virginica
99   6.1  2.8  4.0  1.3  Iris-versicolor
100  5.5  2.6  4.4  1.2  Iris-versicolor
101  7.9  3.8  6.4  2.0   Iris-virginica
102  5.3  3.7  1.5  0.2      Iris-setosa
103  5.1  3.4  1.5  0.2      Iris-setosa
104  7.7  3.8  6.7  2.2   Iris-virginica
105  4.6  3.6  1.0  0.2      Iris-setosa
106  4.5  2.3  1.3  0.3      Iris-setosa
107  6.7  3.0  5.2  2.3   Iris-virginica
108  6.3  3.3  4.7  1.6  Iris-versicolor
109  4.8  3.0  1.4  0.1      Iris-setosa
110  7.2  3.2  6.0  1.8   Iris-virginica
111  6.7  3.3  5.7  2.1   Iris-virginica
112  6.1  3.0  4.9  1.8   Iris-virginica
113  5.0  3.2  1.2  0.2      Iris-setosa
114  7.0  3.2  4.7  1.4  Iris-versicolor
115  5.6  2.9  3.6  1.3  Iris-versicolor
116  6.3  2.5  5.0  1.9   Iris-virginica
117  5.7  2.9  4.2  1.3  Iris-versicolor
118  6.2  2.2  4.5  1.5  Iris-versicolor
119  6.9  3.1  5.4  2.1   Iris-virginica

[120 rows x 5 columns]

In [46]:
test

0    1    2    3                4
0   5.0  3.6  1.4  0.2      Iris-setosa
1   7.7  3.0  6.1  2.3   Iris-virginica
2   6.2  3.4  5.4  2.3   Iris-virginica
3   6.5  3.0  5.2  2.0   Iris-virginica
4   6.3  2.7  4.9  1.8   Iris-virginica
5   4.8  3.1  1.6  0.2      Iris-setosa
6   6.8  3.2  5.9  2.3   Iris-virginica
7   6.7  2.5  5.8  1.8   Iris-virginica
8   6.8  3.0  5.5  2.1   Iris-virginica
9   5.7  2.5  5.0  2.0   Iris-virginica
10  5.7  2.8  4.1  1.3  Iris-versicolor
11  5.5  2.4  3.8  1.1  Iris-versicolor
12  5.5  2.4  3.7  1.0  Iris-versicolor
13  5.2  3.4  1.4  0.2      Iris-setosa
14  6.0  2.7  5.1  1.6  Iris-versicolor
15  6.6  3.0  4.4  1.4  Iris-versicolor
16  6.2  2.9  4.3  1.3  Iris-versicolor
17  4.9  3.1  1.5  0.1      Iris-setosa
18  6.4  2.7  5.3  1.9   Iris-virginica
19  4.6  3.4  1.4  0.3      Iris-setosa
20  4.9  3.0  1.4  0.2      Iris-setosa
21  5.9  3.0  4.2  1.5  Iris-versicolor
22  6.7  3.3  5.7  2.5   Iris-virginica
23  5.9  3.0  5.1  1.8   Iris-virginica
24  6.0  3.0  4.8  1.8   Iris-virginica
25  6.4  3.1  5.5  1.8   Iris-virginica
26  7.1  3.0  5.9  2.1   Iris-virginica
27  5.1  3.3  1.7  0.5      Iris-setosa
28  4.7  3.2  1.3  0.2      Iris-setosa
29  6.4  2.9  4.3  1.3  Iris-versicolor

In [47]:
def gnb_classify(train,test):
    labels = train.iloc[:,-1].value_counts().index #提取训练集的标签种类
    mean =[] #存放每个类别的均值
    std =[] #存放每个类别的方差
    result = [] #存放测试集的预测结果
    for i in labels:
        item = train.loc[train.iloc[:,-1]==i,:] #分别提取出每一种类别
        m = item.iloc[:,:-1].mean() #当前类别的平均值
        s = np.sum((item.iloc[:,:-1]-m)**2)/(item.shape[0]) #当前类别的方差
        mean.append(m) #将当前类别的平均值追加至列表
        std.append(s) #将当前类别的方差追加至列表
    means = pd.DataFrame(mean,index=labels) #变成DF格式，索引为类标签
    stds = pd.DataFrame(std,index=labels) #变成DF格式，索引为类标签
    for j in range(test.shape[0]):
        iset = test.iloc[j,:-1].tolist() #当前测试实例
        iprob = np.exp(-1*(iset-means)**2/(stds*2))/(np.sqrt(2*np.pi*stds)) #正态分布公式
        prob = 1 #初始化当前实例总概率
        for k in range(test.shape[1]-1): #遍历每个特征
            prob *= iprob[k] #特征概率之积即为当前实例概率
            cla = prob.index[np.argmax(prob.values)] #返回最大概率的类别
        result.append(cla)
    test['predict']=result
    acc = (test.iloc[:,-1]==test.iloc[:,-2]).mean() #计算预测准确率
    print(f'模型预测准确率为{acc}')
    return test

In [62]:
gnb_classify(train,test)

模型预测准确率为1.0


0    1    2    3                4          predict
0   5.0  3.6  1.4  0.2      Iris-setosa      Iris-setosa
1   7.7  3.0  6.1  2.3   Iris-virginica   Iris-virginica
2   6.2  3.4  5.4  2.3   Iris-virginica   Iris-virginica
3   6.5  3.0  5.2  2.0   Iris-virginica   Iris-virginica
4   6.3  2.7  4.9  1.8   Iris-virginica   Iris-virginica
5   4.8  3.1  1.6  0.2      Iris-setosa      Iris-setosa
6   6.8  3.2  5.9  2.3   Iris-virginica   Iris-virginica
7   6.7  2.5  5.8  1.8   Iris-virginica   Iris-virginica
8   6.8  3.0  5.5  2.1   Iris-virginica   Iris-virginica
9   5.7  2.5  5.0  2.0   Iris-virginica   Iris-virginica
10  5.7  2.8  4.1  1.3  Iris-versicolor  Iris-versicolor
11  5.5  2.4  3.8  1.1  Iris-versicolor  Iris-versicolor
12  5.5  2.4  3.7  1.0  Iris-versicolor  Iris-versicolor
13  5.2  3.4  1.4  0.2      Iris-setosa      Iris-setosa
14  6.0  2.7  5.1  1.6  Iris-versicolor  Iris-versicolor
15  6.6  3.0  4.4  1.4  Iris-versicolor  Iris-versicolor
16  6.2  2.9  4.3  1.3  Iris-versicolor  Iris-versicolor
17  4.9  3.1  1.5  0.1      Iris-setosa      Iris-setosa
18  6.4  2.7  5.3  1.9   Iris-virginica   Iris-virginica
19  4.6  3.4  1.4  0.3      Iris-setosa      Iris-setosa
20  4.9  3.0  1.4  0.2      Iris-setosa      Iris-setosa
21  5.9  3.0  4.2  1.5  Iris-versicolor  Iris-versicolor
22  6.7  3.3  5.7  2.5   Iris-virginica   Iris-virginica
23  5.9  3.0  5.1  1.8   Iris-virginica   Iris-virginica
24  6.0  3.0  4.8  1.8   Iris-virginica   Iris-virginica
25  6.4  3.1  5.5  1.8   Iris-virginica   Iris-virginica
26  7.1  3.0  5.9  2.1   Iris-virginica   Iris-virginica
27  5.1  3.3  1.7  0.5      Iris-setosa      Iris-setosa
28  4.7  3.2  1.3  0.2      Iris-setosa      Iris-setosa
29  6.4  2.9  4.3  1.3  Iris-versicolor  Iris-versicolor

In [63]:
for i in range(20):
    train,test= randSplit(dataSet, 0.8)
    gnb_classify(train,test)

模型预测准确率为0.9666666666666667
模型预测准确率为0.9666666666666667
模型预测准确率为0.9
模型预测准确率为0.9666666666666667
模型预测准确率为0.9666666666666667
模型预测准确率为0.9666666666666667
模型预测准确率为0.9666666666666667
模型预测准确率为1.0
模型预测准确率为0.9666666666666667
模型预测准确率为1.0
模型预测准确率为1.0
模型预测准确率为0.9666666666666667
模型预测准确率为0.9
模型预测准确率为0.9666666666666667
模型预测准确率为0.9333333333333333
模型预测准确率为0.9666666666666667
模型预测准确率为0.9333333333333333
模型预测准确率为0.9
模型预测准确率为0.8666666666666667
模型预测准确率为0.9333333333333333


In [48]:
labels = train.iloc[:,-1].value_counts().index

In [49]:
labels

Index(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype='object')

In [51]:
i = labels[0]

In [52]:
i

'Iris-setosa'

In [53]:
item = train.loc[train.iloc[:,-1]==i,:] 
item

0    1    2    3            4
0    5.2  3.5  1.5  0.2  Iris-setosa
2    4.8  3.0  1.4  0.3  Iris-setosa
4    4.8  3.4  1.9  0.2  Iris-setosa
5    4.9  3.1  1.5  0.1  Iris-setosa
6    5.1  3.8  1.6  0.2  Iris-setosa
13   5.8  4.0  1.2  0.2  Iris-setosa
21   5.4  3.7  1.5  0.2  Iris-setosa
22   5.0  3.3  1.4  0.2  Iris-setosa
24   4.8  3.4  1.6  0.2  Iris-setosa
25   5.0  3.4  1.5  0.2  Iris-setosa
26   5.5  3.5  1.3  0.2  Iris-setosa
28   4.7  3.2  1.6  0.2  Iris-setosa
33   4.9  3.1  1.5  0.1  Iris-setosa
37   4.6  3.2  1.4  0.2  Iris-setosa
39   5.0  3.0  1.6  0.2  Iris-setosa
42   4.4  2.9  1.4  0.2  Iris-setosa
46   5.1  3.8  1.5  0.3  Iris-setosa
50   5.2  4.1  1.5  0.1  Iris-setosa
51   5.1  3.8  1.9  0.4  Iris-setosa
52   5.7  3.8  1.7  0.3  Iris-setosa
55   5.4  3.9  1.7  0.4  Iris-setosa
59   5.4  3.4  1.5  0.4  Iris-setosa
64   5.0  3.4  1.6  0.4  Iris-setosa
65   5.7  4.4  1.5  0.4  Iris-setosa
67   4.4  3.2  1.3  0.2  Iris-setosa
70   4.3  3.0  1.1  0.1  Iris-setosa
71   4.6  3.1  1.5  0.2  Iris-setosa
73   5.0  3.5  1.6  0.6  Iris-setosa
77   5.1  3.7  1.5  0.4  Iris-setosa
81   5.1  3.5  1.4  0.3  Iris-setosa
82   4.4  3.0  1.3  0.2  Iris-setosa
85   5.1  3.5  1.4  0.2  Iris-setosa
88   5.4  3.9  1.3  0.4  Iris-setosa
90   5.5  4.2  1.4  0.2  Iris-setosa
93   5.4  3.4  1.7  0.2  Iris-setosa
94   5.0  3.5  1.3  0.3  Iris-setosa
102  5.3  3.7  1.5  0.2  Iris-setosa
103  5.1  3.4  1.5  0.2  Iris-setosa
105  4.6  3.6  1.0  0.2  Iris-setosa
106  4.5  2.3  1.3  0.3  Iris-setosa
109  4.8  3.0  1.4  0.1  Iris-setosa
113  5.0  3.2  1.2  0.2  Iris-setosa

In [54]:
mean =[] #存放每个类别的均值
std =[] #存放每个类别的方差
result = [] #存放测试集的预测结果
for i in labels:
    item = train.loc[train.iloc[:,-1]==i,:] #分别提取出每一种类别
    m = item.iloc[:,:-1].mean() #当前类别的平均值
    s = np.sum((item.iloc[:,:-1]-m)**2)/(item.shape[0]) #当前类别的方差
    mean.append(m) #将当前类别的平均值追加至列表
    std.append(s) #将当前类别的方差追加至列表

In [55]:
mean

[0    5.026190
 1    3.447619
 2    1.464286
 3    0.245238
 dtype: float64, 0    5.928571
 1    2.771429
 2    4.264286
 3    1.328571
 dtype: float64, 0    6.616667
 1    2.980556
 2    5.597222
 3    2.022222
 dtype: float64]

In [56]:
std

[0    0.135743
 1    0.157256
 2    0.032296
 3    0.011049
 dtype: float64, 0    0.282993
 1    0.104898
 2    0.227058
 3    0.039184
 dtype: float64, 0    0.451389
 1    0.114900
 2    0.347492
 3    0.082284
 dtype: float64]

In [57]:
means = pd.DataFrame(mean,index=labels) #变成DF格式，索引为类标签
stds = pd.DataFrame(std,index=labels) #变成DF格式，索引为类标签

In [58]:
means

0         1         2         3
Iris-setosa      5.026190  3.447619  1.464286  0.245238
Iris-versicolor  5.928571  2.771429  4.264286  1.328571
Iris-virginica   6.616667  2.980556  5.597222  2.022222

In [59]:
stds

0         1         2         3
Iris-setosa      0.135743  0.157256  0.032296  0.011049
Iris-versicolor  0.282993  0.104898  0.227058  0.039184
Iris-virginica   0.451389  0.114900  0.347492  0.082284

In [60]:
for j in range(test.shape[0]):
    iset = test.iloc[j,:-1].tolist() #当前测试实例
    iprob = np.exp(-1*(iset-means)**2/(stds*2))/(np.sqrt(2*np.pi*stds)) #正态分布公式
    prob = 1 #初始化当前实例总概率
    for k in range(test.shape[1]-1): #遍历每个特征
        prob *= iprob[k] #特征概率之积即为当前实例概率
        cla = prob.index[np.argmax(prob.values)] #返回最大概率的类别
    result.append(cla)

In [61]:
result

['Iris-setosa',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-setosa',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-setosa',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-versicolor',
 'Iris-setosa',
 'Iris-virginica',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-versicolor',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-virginica',
 'Iris-setosa',
 'Iris-setosa',
 'Iris-versicolor']

In [64]:
##文档分类案例

In [65]:
def loadDataSet():
    dataSet=[['my', 'dog', 'has', 'flea', 'problems', 'help', 'please'],
             ['maybe', 'not', 'take', 'him', 'to', 'dog', 'park', 'stupid'],
             ['my', 'dalmation', 'is', 'so', 'cute', 'I', 'love', 'him'],
             ['stop', 'posting', 'stupid', 'worthless', 'garbage'],
             ['mr', 'licks', 'ate', 'my', 'steak', 'how', 'to', 'stop', 'him'],
             ['quit', 'buying', 'worthless', 'dog', 'food', 'stupid']] #切分好的词条
    classVec = [0,1,0,1,0,1] #类别标签向量，1代表侮辱性词汇，0代表非侮辱性词汇
    return dataSet,classVec

In [66]:
dataSet,classVec = loadDataSet()

In [67]:
dataSet

[['my', 'dog', 'has', 'flea', 'problems', 'help', 'please'],
 ['maybe', 'not', 'take', 'him', 'to', 'dog', 'park', 'stupid'],
 ['my', 'dalmation', 'is', 'so', 'cute', 'I', 'love', 'him'],
 ['stop', 'posting', 'stupid', 'worthless', 'garbage'],
 ['mr', 'licks', 'ate', 'my', 'steak', 'how', 'to', 'stop', 'him'],
 ['quit', 'buying', 'worthless', 'dog', 'food', 'stupid']]

In [68]:
classVec

[0, 1, 0, 1, 0, 1]

In [69]:
def createVocabList(dataSet):
    vocabSet = set() #创建一个空的集合
    for doc in dataSet: #遍历dataSet中的每一条言论
        vocabSet = vocabSet | set(doc) #取并集
        vocabList = list(vocabSet)
    return vocabList

In [70]:
vocabList = createVocabList(dataSet)

In [72]:
print(vocabList)

['posting', 'dog', 'my', 'steak', 'please', 'problems', 'buying', 'stupid', 'food', 'is', 'how', 'worthless', 'maybe', 'ate', 'take', 'mr', 'not', 'him', 'I', 'help', 'flea', 'so', 'licks', 'garbage', 'quit', 'park', 'love', 'cute', 'dalmation', 'has', 'to', 'stop']


In [73]:
def setOfWords2Vec(vocabList, inputSet):
    returnVec = [0] * len(vocabList) #创建一个其中所含元素都为0的向量
    for word in inputSet: #遍历每个词条
        if word in vocabList: #如果词条存在于词汇表中，则变为1
            returnVec[vocabList.index(word)] = 1
        else:
            print(f" {word} is not in my Vocabulary!" )
    return returnVec #返回文档向量

In [74]:
def get_trainMat(dataSet):
    trainMat = [] #初始化向量列表
    vocabList = createVocabList(dataSet) #生成词汇表
    for inputSet in dataSet: #遍历样本词条中的每一条样本
        returnVec=setOfWords2Vec(vocabList, inputSet) #将当前词条向量化
        trainMat.append(returnVec) #追加到向量列表中
    return trainMat

In [75]:
trainMat = get_trainMat(dataSet)

In [76]:
print(trainMat)

[[0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0], [0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0], [0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0], [1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1], [0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]]


In [77]:
def trainNB(trainMat,classVec):
    n = len(trainMat) #计算训练的文档数目
    m = len(trainMat[0]) #计算每篇文档的词条数
    pAb = sum(classVec)/n #文档属于侮辱类的概率
    p0Num = np.zeros(m) #词条出现数初始化为0
    p1Num = np.zeros(m) #词条出现数初始化为0
    p0Denom = 0 #分母初始化为0
    p1Denom = 0 #分母初始化为0
    for i in range(n): #遍历每一个文档
        if classVec[i] == 1: #统计属于侮辱类的条件概率所需的数据
            p1Num += trainMat[i]
            p1Denom += sum(trainMat[i])
        else: #统计属于非侮辱类的条件概率所需的数据
            p0Num += trainMat[i]
            p0Denom += sum(trainMat[i])
    p1V = p1Num/p1Denom
    p0V = p0Num/p0Denom
    return p0V,p1V,pAb #返回属于非侮辱类,侮辱类和文档属于侮辱类的概率

In [78]:
p0V,p1V,pAb=trainNB(trainMat,classVec)

In [83]:
print(vocabList)

['posting', 'dog', 'my', 'steak', 'please', 'problems', 'buying', 'stupid', 'food', 'is', 'how', 'worthless', 'maybe', 'ate', 'take', 'mr', 'not', 'him', 'I', 'help', 'flea', 'so', 'licks', 'garbage', 'quit', 'park', 'love', 'cute', 'dalmation', 'has', 'to', 'stop']


In [79]:
p0V

array([0.        , 0.04166667, 0.125     , 0.04166667, 0.04166667,
       0.04166667, 0.        , 0.        , 0.        , 0.04166667,
       0.04166667, 0.        , 0.        , 0.04166667, 0.        ,
       0.04166667, 0.        , 0.08333333, 0.04166667, 0.04166667,
       0.04166667, 0.04166667, 0.04166667, 0.        , 0.        ,
       0.        , 0.04166667, 0.04166667, 0.04166667, 0.04166667,
       0.04166667, 0.04166667])

In [80]:
p1V

array([0.05263158, 0.10526316, 0.        , 0.        , 0.        ,
       0.        , 0.05263158, 0.15789474, 0.05263158, 0.        ,
       0.        , 0.10526316, 0.05263158, 0.        , 0.05263158,
       0.        , 0.05263158, 0.05263158, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.05263158, 0.05263158,
       0.05263158, 0.        , 0.        , 0.        , 0.        ,
       0.05263158, 0.05263158])

In [81]:
pAb

0.5

In [84]:
from functools import reduce

In [85]:
def classifyNB(vec2Classify, p0V, p1V, pAb):
    p1 = reduce(lambda x,y:x*y, vec2Classify * p1V) * pAb   #对应元素相乘
    p0 = reduce(lambda x,y:x*y, vec2Classify * p0V) * (1 - pAb)
    print('p0:',p0)
    print('p1:',p1)
    if p1 > p0:
        return 1
    else:
        return 0


In [97]:
def testingNB(testVec):
    dataSet,classVec = loadDataSet() #创建实验样本
    vocabList = createVocabList(dataSet) #创建词汇表
    trainMat= get_trainMat(dataSet) #将实验样本向量化
    p0V,p1V,pAb = trainNB(trainMat,classVec) #训练朴素贝叶斯分类器
    thisone = setOfWords2Vec(vocabList, testVec) #测试样本向量化
    if classifyNB(thisone,p0V,p1V,pAb):
        print(testVec,'属于侮辱类') #执行分类并打印分类结果
    else:
        print(testVec,'属于非侮辱类') #执行分类并打印分类结果

In [87]:
#测试样本1
testVec1 = ['love', 'my', 'dalmation']
testingNB(testVec1)

p0: 0.0
p1: 0.0
['love', 'my', 'dalmation'] 属于非侮辱类


In [88]:
#测试样本2
testVec2 = ['stupid', 'garbage']
testingNB(testVec2)

p0: 0.0
p1: 0.0
['stupid', 'garbage'] 属于非侮辱类


In [107]:
def trainNB(trainMat,classVec):
    n = len(trainMat) #计算训练的文档数目
    m = len(trainMat[0]) #计算每篇文档的词条数
    pAb = sum(classVec)/n #文档属于侮辱类的概率
    p0Num = np.ones(m) #词条出现数初始化为1
    p1Num = np.ones(m) #词条出现数初始化为1
    p0Denom = 2 #分母初始化为2
    p1Denom = 2 #分母初始化为2
    for i in range(n): #遍历每一个文档
        if classVec[i] == 1: #统计属于侮辱类的条件概率所需的数据
            p1Num += trainMat[i]
            p1Denom += sum(trainMat[i])
        else: #统计属于非侮辱类的条件概率所需的数据
            p0Num += trainMat[i]
            p0Denom += sum(trainMat[i])
    p1V = np.log(p1Num/p1Denom)
    p0V = np.log(p0Num/p0Denom)
    return p0V,p1V,pAb #返回属于非侮辱类,侮辱类和文档属于侮辱类的概率

In [108]:
p0V,p1V,pAb=trainNB(trainMat,classVec)

In [109]:
p0V

array([-3.25809654, -2.56494936, -1.87180218, -2.56494936, -2.56494936,
       -2.56494936, -3.25809654, -3.25809654, -3.25809654, -2.56494936,
       -2.56494936, -3.25809654, -3.25809654, -2.56494936, -3.25809654,
       -2.56494936, -3.25809654, -2.15948425, -2.56494936, -2.56494936,
       -2.56494936, -2.56494936, -2.56494936, -3.25809654, -3.25809654,
       -3.25809654, -2.56494936, -2.56494936, -2.56494936, -2.56494936,
       -2.56494936, -2.56494936])

In [110]:
p1V

array([-2.35137526, -1.94591015, -3.04452244, -3.04452244, -3.04452244,
       -3.04452244, -2.35137526, -1.65822808, -2.35137526, -3.04452244,
       -3.04452244, -1.94591015, -2.35137526, -3.04452244, -2.35137526,
       -3.04452244, -2.35137526, -2.35137526, -3.04452244, -3.04452244,
       -3.04452244, -3.04452244, -3.04452244, -2.35137526, -2.35137526,
       -2.35137526, -3.04452244, -3.04452244, -3.04452244, -3.04452244,
       -2.35137526, -2.35137526])

In [111]:
pAb

0.5

In [94]:
def classifyNB(vec2Classify, p0V, p1V, pAb):
    p1 = sum(vec2Classify * p1V) + np.log(pAb)    #对应元素相乘
    p0 = sum(vec2Classify * p0V) + np.log(1- pAb) #对应元素相乘
    if p1 > p0:
        return 1
    else:
        return 0

In [112]:
#测试样本1
testVec1 = ['love', 'my', 'dalmation']
testingNB(testVec1)

['love', 'my', 'dalmation'] 属于非侮辱类


In [113]:
#测试样本2
testVec2 = ['stupid', 'garbage']
testingNB(testVec2)

['stupid', 'garbage'] 属于侮辱类


In [103]:
def testingNB(testVec):
    dataSet,classVec = loadDataSet() #创建实验样本
    vocabList = createVocabList(dataSet) #创建词汇表
    trainMat= get_trainMat(dataSet) #将实验样本向量化
    p0V,p1V,pAb = trainNB(trainMat,classVec) #训练朴素贝叶斯分类器
    thisone = setOfWords2Vec(vocabList, testVec) #测试样本向量化
    if classifyNB(thisone,p0V,p1V,pAb):
        print(testVec,'属于侮辱类') #执行分类并打印分类结果
    else:
        print(testVec,'属于非侮辱类') #执行分类并打印分类结果